version: '3.9'
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: swissbobo/frontend-prod:v1
    volumes:
      - ./frontend/src:/app/frontend/src
      - build:/app/frontend/build
    env_file:
      - ./frontend/env-docker/.prod.env
    command: "npm run build"
    
  nginx:
    ports:
      - ${HOST_SERVER_PORT}:${CONT_SERVER_PORT}
    volumes:
      - build:/usr/share/nginx/html
    depends_on:
      - frontend

volumes:
  build: